composer:
  build: ./docker/composer
  volumes_from: 
    - files

files:
  image: alpine:3.4
  volumes:
    - .:/data/www/site
  command: /bin/ash


chat1:
  build: ./docker/php
  ports:
    - "8081:8080"
  volumes_from:
    - files
  links: 
   - rabbit

chat2:
  build: ./docker/php
  ports:
    - "8082:8080"
  volumes_from:
    - files    
  links: 
   - rabbit

chat3:
  build: ./docker/php
  ports:
    - "8083:8080"
  volumes_from:
    - files    
  links: 
   - rabbit

rabbit:
  image: rabbitmq:management-alpine
  environment:
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=password
    - RABBITMQ_DEFAULT_VHOST=rabbit
  ports:
     - "8080:15672"

